### ISSUE TITLE
internal server error when trying to filter results by Evidence Type

### ISSUE THREAD

**Issue by joseempa** [dwyl/best-evidence#175] opened 2017-08-29 14:05 UTC
This is a very useful characteristic when doing searches. This allows me to reduce the numbr of pertinent results.

I get the same problem from mobile and desktop access.

**Comment by markwilliamfirth** [comment] 2017-08-30 06:00
@SimonLab please could you time estimate this bug?

**Comment by SimonLab** [comment] 2017-08-30 10:43
Thanks @joseempa for spotting this.
I start to investigate what is causing the error.

@markwilliamfirth I'm not sure how long it's going to take to fix as I don't know yet the cause but I will update this issue as soon as I have find more information

**Comment by SimonLab** [comment] 2017-08-30 11:02
From heroku logs:
![image](https://user-images.githubusercontent.com/6057298/29868921-bad4845c-8d78-11e7-94a2-89f3b6075187.png)

It seems that our result search page try to use a variable (search_changeset) which is not defined when a filter is selected. I think the search_changeset variable is used to represent the search box at the top of the page.
I'm going to check that all of our template are up to date.

**Comment by SimonLab** [comment] 2017-08-30 11:04
A new PR (https://github.com/dwyl/best-evidence/pull/174) will resolve this issue. We have refactor some template and code structure so this should be fine when the PR is merged

**Comment by SimonLab** [comment] 2017-08-30 15:10
@joseempa this should be resolved now. Let us know if you still have this issue, thanks

**Comment by ajburls** [comment] 2017-08-30 15:28
@joseempa Thanks @SimonLab this now working properly again, so closed on Jose's behalf.

**Closed by ajburls** 2017-08-30 15:28 UTC
Labels: bug, please-test, priority-1
