### ISSUE TITLE
Persistent problems with log in and inconsistencies in history

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#113] opened 2017-08-09 13:02 UTC
I noticed that the history was different in the record shown online than the record shown on my phone.

The record online showed searches that I had done going back a long time even though Simon had deleted my ajburls@yahoo.co.uk account and I had recreated it earlier today on my phone.

The history on phone was only since I recreated the account.

So I deleted cookies on my computer so that I had to log in again to see what history I got. However, I am not able to log in online with my ajburls account that I just recreated :-(

**Comment by markwilliamfirth** [comment] 2017-08-09 13:05
@ajburls can you confirm which app you are using for each of these cases? Is it:

best-evidence-staging.herokuapp.com

or

best-evidence-app.herokuapp.com

**Comment by ajburls** [comment] 2017-08-09 13:09
@markwilliamfirth 

best-evidence-staging.herokuapp.com for both

**Comment by markwilliamfirth** [comment] 2017-08-09 13:23
@SimonLab please can you look into this bug on best-evidence-staging.herokuapp.com?

- Desktop app showed historical record of searches for a newly created account that was previously deleted (ajburls@yahoo.co.uk), whilst the mobile app did not show historical searches
- Deleting cookies did not resolve the issue, instead Amanda is not able to log in to the app

**Comment by SimonLab** [comment] 2017-08-09 13:39
@markwilliamfirth @ajburls the database on staging is changing and will change with the notes feature. So unfortunately this means that the staging database is not fully stable and some data conflict can occur as the application is still in development (however the production database is stable). This might be why @ajburls you have some issues to login and see the same data on the history page.

I've checked again the logic of the code and tested the application on my mobile and desktop and unfortunately I can't reproduce the bugs.

I would suggest to reset all the staging database to start with an empty application. This will help us to target bugs if they occur again. @ajburls does this sound good?

**Comment by ajburls** [comment] 2017-08-09 15:14
@SimonLab @markwilliamfirth 
Yes, good plan, please do re-set everything and I will create my ajburls@yahoo.co.uk account again when you signal this is done and check whether problems are resolved.

You should also delete of the fictitious emails I created like mad@gmail.com and rubbish5!

Thanks

Amanda

**Comment by markwilliamfirth** [comment] 2017-08-10 17:40
Next step:

- [ ] Simon to reset the staging database

**Comment by SimonLab** [comment] 2017-08-21 14:50
@ajburls is now a good moment for us to reset the database? We have now deploy the "note publication" feature but we need to delete the current structure of the database to make it work. I just wanted to make sure that you are not currently using it before we delete everything.

**Comment by ajburls** [comment] 2017-08-21 15:00
@SimonLab Yes

**Comment by SimonLab** [comment] 2017-08-21 15:08
@ajburls The database is no empty, you will need to create a new account. You should now also be able to test the notes on searches and publications

**Comment by ajburls** [comment] 2017-08-21 15:18
@SimonLab The history on the laptop and on iPhone now consistent. iPhone is still requiring me to login if I have closed the app. I will test on my Android when I find it :-)

**Comment by ajburls** [comment] 2017-08-21 16:09
@SimonLab I tested this on Android and all is consistent (It wouldn't let me login but it let me register a new account with the same log in details as the old account. )

**Comment by markwilliamfirth** [comment] 2017-08-21 16:20
Related to #88

**Comment by markwilliamfirth** [comment] 2017-08-22 12:06
@ajburls thanks for confirming that history is now consistent, we can now close this issue and I've linked to the logging in issue above so we know that bug is recorded there again too (we'll close this one in favour of that issue)

**Closed by markwilliamfirth** 2017-08-22 12:06 UTC
Labels: bug, please-test, priority-1, T25m
